name: On Push

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  lint_and_build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build
